### PR TITLE
Update linter to work with SublimeLinter 4, remove unneeded overrides of superclass

### LINKED ISSUE #5: No longer working. Error messages in console
Hi, thanks for this package, has been working great for me for the last ~18 months.

However, recently stopped working and I'm not sure why. When I open Sublime Text I get these errors in console:
```
SublimeLinter: ERROR:
=====================

swiftlint: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

swiftlint: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.


SublimeLinter: ERROR:
=====================

swiftlint disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector
```

I'm using swiftlint 0.34.0, SublimeLinter 4.12.0, SublimeLinter-contrib-swiftlint 0.10.0.

Any idea how to fix this? 

Thanks!

### PR DESCRIPTION
**Pull request by kmahar**
Fixes #5 plus a few other changes. 

* `util` import is unused, caught by flake8
* `syntax`, `executable`, `version_args`,  `version_re`, `version_requirement`, `config_file`, `inline_settings`, `inline_overrides`, `comment_re`, `selectors`  no longer have any effect
* SublimeLinter template's [HOWTO.md](https://github.com/SublimeLinter/SublimeLinter-template/blob/master/HOWTO.md) says you should remove unchanged attributes (I agree, it makes it confusing what's an override and what isn't) so I've removed `multiline`, `line_col_base`, `tempfile_suffix`, `error_stream`
* it's now required that `defaults` contains a `selector`, so added that (this is what broke the plugin in the first place, see SublimeLinter/SublimeLinter#1578)
* I also took out the `word_re` override to `None`, as it means only the first character of the relevant word gets highlighted, and I find it easier to spot the violation when the whole word gets selected.

Anyway, feel free to accept or reject as much of this as you'd like, and thanks again for this package, has been super useful to me for a while now!

### CODE REVIEW

**Comment by mailiam** [comment]
Great thanks! I haven’t been using sublime for a while to test these. Would you mind me adding you to project member to manage project?

**Comment by kmahar** [comment]
@mailiam sure!

**Comment by mailiam** [comment]
@kmahar does this PR fixes #4 as well?

**Comment by kmahar** [comment]
I'm not really sure what the issue to begin with was there. I did not have any trouble installing this package via Package Control myself. So I would say we can close it and let the user know to open a new issue or reopen if they are still having problems.

In the next few days I will try to update the README to reflect new version info for SublimeLinter (3 -> 4), and then do a release so the new changes in this PR will be installable via Package Control.

**Comment by mailiam** [comment]
Thank you @kmahar 
Please feel free to contribute as much as you can. I will try my best to support. Start with installing sublime text again :]

**Pull request merged**
